spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securityupdate
    username: postgres
    password: Azertyui1*
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate :
      ddl-auto: create
      format_sql : true




